### ISSUE TITLE
Download Link Is Broken

### ISSUE THREAD

**Issue by AhmedHatemAhmed** [ice1000/Dekoder#4]
**Please update jar download link**
Thank you!

**Comment by ice1000** [comment]
See the release page:

https://github.com/ice1000/Dekoder/releases/download/v1.3.1/dekoder.jar

I'm going to fix it. Thx for your feed back

**Comment by ice1000** [comment]
I've done some update

**Comment by ice1000** [comment]
please review them :+1:
